CREATE DATABASE IF NOT EXISTS rasa;
USE rasa;

CREATE TABLE PERSON (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL, 
    password VARCHAR(50) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE USER if not exists 'rasauser'
	IDENTIFIED BY 'rasapassword';
    GRANT ALL PRIVILEGES ON PERSON.* TO rasauser;